


// Date: May 5th, 2025: 
// Author: Evan Wu 

/* alu_defs.vh  */
// Definition of alu_op signals generated by inst_decode.v that are used the ALU module
// defined in ALU.v

`define ALU_ADD 3'b000
`define ALU_SUB 3'b001
`define ALU_AND 3'b010
`define ALU_OR  3'b011



    